### PR TITLE
TPC-324

### PR DESCRIPTION
**Pull request by CameronDeacon**
- [x] Tests for the changes have been added (for bug fixes / features)

- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Adds 2 new args:
1. to create the new pages as a child page (as required for the new confluence layout)
2. flag to allow for files in the /docs folder only to be copied across

New naming convention for file / folder names on confluence
Also fixes the relative linking problem for both links and images
Multiple relative links can appear on the same line
Updated the tool to use Go 1.18 and golangci-lint to 1.50.1

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No can continue using an old tag if desired

### CODE REVIEW

**Review by ianhaycox — DISMISSED** [review]
Really nice work.

This is a huge improvement and makes the tool much more useful.

**Review by timchurchard — APPROVED** [review]

**Review by ricktimmis-xia — APPROVED** [review]
Wow!! Well Done. This is a massive clean up, and improvement. Can't wait to see this Show_n_Tell at TDA.
Great Work!!

**Comment by ricktimmis-xia** [comment]
Looks awesome @CameronDeacon Show_n_Tell at TDA, and then it's good to merge

**Review by SamBrooks-Martin — APPROVED** [review]
Really fantastic update mate - only one comment from me. 

In the test output in Confluence, I noticed that the name of each file and folder seems to include the path up until that point. This isn't the case in the source GitHub repo of course, and the full path of the page is given at the top of the confluence page anyway, e.g.:
image
image

I'm wondering if we can either make this toggleable, or remove it as it makes each path in confluence a little too verbose to me. I couldn't find the exact code where this is handled so if this has been changed already do ignore me :)

Happy to approve though 👍. Cheers for the hard work!

**Comment by CameronDeacon** [comment]
Thanks Sam 👍 

Yes that was what I wanted to do too - but the way confluence works is that every page in a space must have a unique title.

i.e.
imagine if in a repo we had a file called Product.md in both the /dataflows and /connectors folders. If we try to copy that across to confluence it will create the first one, then the second one will find the previously created page called Product.md and overwrite it.

It is a flaw in confluence really - even though the 2 pages have the same name but are in sub-pages (sub-directories) it still needs to be unique.

So the compromise I think is best is to just have the file or folder name followed by the absolute path in brackets (that way the name should always be unique).

Happy to update it to something else :)

**Review by timchurchard — APPROVED** [review]

**Review by SamBrooks-Martin — APPROVED** [review]

**Pull request merged**
